// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// Assemble the published stylesheet. Runs after tsup (via the `onSuccess` hook
// in tsup.config.ts) so the compiled theme module is available to import.
//
// It produces four kinds of file under dist/:
//   - theme/framework.css — the static structural stylesheet, copied verbatim
//     from src so it can be imported on its own (the runtime-presets path).
//   - styles.css — the one-import bundle: the static stylesheet plus the
//     colour blocks for *every* built-in theme, with an `@source` so a
//     consumer's Tailwind build scans the framework's emitted utility classes.
//     This is the zero-config path: `@import` it and the framework paints in
//     every built-in theme.
//   - styles/base.css — the same bundle with no theme colours in it at all.
//   - styles/theme/<id>.css — one theme's colour block, on its own.
//
// The last two are the pay-for-what-you-use path. CSS is the one part of the
// package a bundler cannot shake: thirteen palettes are ~6 KB of custom
// properties that an app offering two themes still ships in full. Splitting
// them lets that app import the base plus its two, and the numbers stay
// honest because all four files are generated from the same PRESET_PALETTES.
//
// Generating from the compiled `PRESET_TOKENS_CSS` keeps the colours in lockstep
// with the framework's palette data — there is no second hand-written copy to
// drift.

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import {
  PRESET_TOKENS_BY_THEME,
  PRESET_TOKENS_CSS,
} from "../dist/theme/index.js";

const here = (p) => fileURLToPath(new URL(p, import.meta.url));

const frameworkCss = readFileSync(here("../src/theme/framework.css"), "utf8");

// Copy the static stylesheet into dist so it is importable on its own
// (`@niclaslindstedt/oss-framework/theme/framework.css`).
mkdirSync(here("../dist/theme"), { recursive: true });
writeFileSync(here("../dist/theme/framework.css"), frameworkCss);

// The one-import bundle. `@source "./"` makes the consumer's Tailwind scan the
// sibling compiled modules in dist/ so their utility classes are emitted; the
// generated preset blocks supply every built-in theme's colours.
const GENERATED =
  `/* SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0 */\n` +
  `/* Generated by scripts/build-styles.mjs — do not edit. */\n`;

const bundle =
  `${GENERATED}\n` +
  `@source "./";\n\n` +
  `${frameworkCss}\n` +
  `/* ── Built-in theme palettes (generated from PRESET_PALETTES) ───────────── */\n` +
  `${PRESET_TOKENS_CSS}\n`;

writeFileSync(here("../dist/styles.css"), bundle);

// The split path. `base.css` is the bundle minus every theme colour; each
// theme file carries one `:root[data-theme="…"]` block. An app imports the base
// and the themes it offers:
//
//   @import "@niclaslindstedt/oss-framework/styles/base.css";
//   @import "@niclaslindstedt/oss-framework/styles/theme/nord.css";
//
// The `@source` is relative to the file that carries it, so it climbs one more
// level here than it does in the flat bundle.
mkdirSync(here("../dist/styles/theme"), { recursive: true });

const base =
  `${GENERATED}\n` +
  `/* The framework's structural styles, with no theme colours. Pair it with\n` +
  `   one or more styles/theme/<id>.css files, or install the colours at\n` +
  `   runtime with installPresetTokens(). */\n\n` +
  `@source "../";\n\n` +
  `${frameworkCss}`;

writeFileSync(here("../dist/styles/base.css"), base);

for (const [theme, block] of Object.entries(PRESET_TOKENS_BY_THEME)) {
  writeFileSync(
    here(`../dist/styles/theme/${theme}.css`),
    `${GENERATED}\n/* The "${theme}" theme's colours. Needs styles/base.css. */\n\n${block}\n`,
  );
}

const themes = Object.keys(PRESET_TOKENS_BY_THEME);
console.log(
  `build-styles: wrote dist/styles.css, dist/theme/framework.css, ` +
    `dist/styles/base.css and ${themes.length} theme files`,
);
