// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// Assemble the published stylesheet. Runs after tsup (via the `onSuccess` hook
// in tsup.config.ts) so the compiled theme module is available to import.
//
// It produces two files under dist/:
//   - theme/framework.css — the static structural stylesheet, copied verbatim
//     from src so it can be imported on its own (the runtime-presets path).
//   - styles.css — the one-import bundle: the static stylesheet plus the
//     per-preset colour blocks generated from PRESET_PALETTES, with an
//     `@source` so a consumer's Tailwind build scans the framework's emitted
//     utility classes. This is the zero-config path: `@import` it and the
//     framework paints in every built-in theme.
//
// Generating from the compiled `PRESET_TOKENS_CSS` keeps the colours in lockstep
// with the framework's palette data — there is no second hand-written copy to
// drift.

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { PRESET_TOKENS_CSS } from "../dist/theme/index.js";

const here = (p) => fileURLToPath(new URL(p, import.meta.url));

const frameworkCss = readFileSync(here("../src/theme/framework.css"), "utf8");

// Copy the static stylesheet into dist so it is importable on its own
// (`@niclaslindstedt/oss-framework/theme/framework.css`).
mkdirSync(here("../dist/theme"), { recursive: true });
writeFileSync(here("../dist/theme/framework.css"), frameworkCss);

// The one-import bundle. `@source "./"` makes the consumer's Tailwind scan the
// sibling compiled modules in dist/ so their utility classes are emitted; the
// generated preset blocks supply every built-in theme's colours.
const bundle =
  `/* SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0 */\n` +
  `/* Generated by scripts/build-styles.mjs — do not edit. */\n\n` +
  `@source "./";\n\n` +
  `${frameworkCss}\n` +
  `/* ── Built-in theme palettes (generated from PRESET_PALETTES) ───────────── */\n` +
  `${PRESET_TOKENS_CSS}\n`;

writeFileSync(here("../dist/styles.css"), bundle);

console.log("build-styles: wrote dist/styles.css and dist/theme/framework.css");
